const PDFDocument = require('pdfkit');
const fs = require('fs').promises;
const path = require('path');
const config = require('../config');

async function generatePDFReport(data) {
    return new Promise(async (resolve, reject) => {
        try {
            // Ensure reports directory exists
            const reportsDir = config.STORAGE.pdfDirectory;
            await fs.mkdir(reportsDir, { recursive: true });
            
            const fileName = `whatsapp_data_${Date.now()}.pdf`;
            const filePath = path.join(reportsDir, fileName);
            
            const doc = new PDFDocument({ margin: 50 });
            const stream = fs.createWriteStream(filePath);
            
            doc.pipe(stream);
            
            // Add header
            doc.fontSize(20)
               .text('WhatsApp Data Collection Report', { align: 'center' });
            
            doc.moveDown();
            doc.fontSize(12)
               .text(`Generated: ${new Date().toLocaleString()}`);
            doc.text(`Total Entries: ${data.length}`);
            doc.text(`Countries: ${Object.keys(config.COUNTRIES).join(', ')}`);
            
            doc.moveDown();
            doc.fontSize(10)
               .text('⚠️ IMPORTANT: This report contains only publicly shared information.', 
                     { color: 'red' });
            doc.text('All data collection complies with privacy laws and platform terms.');
            
            // Group data by country
            const dataByCountry = {};
            data.forEach(entry => {
                if (!dataByCountry[entry.country]) {
                    dataByCountry[entry.country] = [];
                }
                dataByCountry[entry.country].push(entry);
            });
            
            // Generate report for each country
            for (const [country, entries] of Object.entries(dataByCountry)) {
                doc.addPage();
                
                doc.fontSize(16)
                   .text(`Country: ${country}`, { underline: true });
                doc.moveDown();
                
                let yPos = doc.y;
                let index = 0;
                
                for (const entry of entries) {
                    if (yPos > 700) { // Check if we need a new page
                        doc.addPage();
                        yPos = 50;
                    }
                    
                    // Draw entry box
                    doc.roundedRect(50, yPos, 500, 80, 5)
                       .stroke();
                    
                    // Entry content
                    doc.fontSize(10)
                       .text(`Entry #${++index}`, 55, yPos + 5);
                    
                    doc.fontSize(9)
                       .text(`Phone: ${entry.phoneNumber}`, 55, yPos + 20)
                       .text(`Source: ${entry.source}`, 55, yPos + 35)
                       .text(`Category: ${entry.category}`, 55, yPos + 50)
                       .text(`Date: ${new Date(entry.timestamp).toLocaleDateString()}`, 300, yPos + 20)
                       .text(`User: ${entry.username}`, 300, yPos + 35);
                    
                    yPos += 90;
                }
            }
            
            // Add summary page
            doc.addPage();
            doc.fontSize(16)
               .text('Collection Summary', { align: 'center', underline: true });
            
            doc.moveDown();
            
            const summary = {
                'Total Entries': data.length,
                'Unique Countries': Object.keys(dataByCountry).length,
                'Data Range': `${new Date(data[0]?.timestamp).toLocaleDateString()} - ${new Date(data[data.length-1]?.timestamp).toLocaleDateString()}`,
                'Sources Used': [...new Set(data.map(d => d.source))].join(', '),
                'Categories Found': [...new Set(data.map(d => d.category))].join(', ')
            };
            
            Object.entries(summary).forEach(([key, value], i) => {
                doc.fontSize(11)
                   .text(`${key}: ${value}`, 50, 100 + (i * 25));
            });
            
            // Add footer on each page
            const totalPages = doc.bufferedPageRange().count;
            for (let i = 0; i < totalPages; i++) {
                doc.switchToPage(i);
                doc.fontSize(8)
                   .text(`Page ${i + 1} of ${totalPages} | Confidential Report`, 
                         50, 800, { align: 'center' });
                doc.text(`Generated by Public Data Collection Bot | ${new Date().toISOString().split('T')[0]}`,
                         50, 815, { align: 'center' });
            }
            
            doc.end();
            
            stream.on('finish', () => {
                resolve(filePath);
            });
            
            stream.on('error', reject);
            
        } catch (error) {
            reject(error);
        }
    });
}

module.exports = {
    generatePDFReport
};
